### ISSUE TITLE
clang: error: no such file or directory: '@LIBCURL_CPPFLAGS@'

### ISSUE THREAD

**Issue by Hamtar0z** [pooler/cpuminer#279] opened 2024-04-10 10:17 UTC
Basic *nix build instructions:
	./autogen.sh	# only needed if building from git repo
	./nomacro.pl	# in case the assembler doesn't support macros
	./configure CFLAGS="-O3" # make sure -O3 is an O and not a zero!
	make

<img width="1118" alt="Screen Shot 2567-04-10 at 17 16 49" src="https://github.com/pooler/cpuminer/assets/166582787/4d67aabe-b220-4ec8-8476-e638a3a10bd5">

**Comment by pooler** [comment] 2024-04-10 11:06
Duplicate of #278.

**Closed as not planned by pooler** 2024-04-10 11:06 UTC

**Comment by Silentsniper1** [comment] 2024-04-26 14:35
> Basic *nix build instructions: ./autogen.sh # only needed if building from git repo ./nomacro.pl # in case the assembler doesn't support macros ./configure CFLAGS="-O3" # make sure -O3 is an O and not a zero! make
> 
> <img alt="Screen Shot 2567-04-10 at 17 16 49" width="1118" src="https://private-user-images.githubusercontent.com/166582787/321195030-4d67aabe-b220-4ec8-8476-e638a3a10bd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDI0MDAsIm5iZiI6MTcxNDE0MjEwMCwicGF0aCI6Ii8xNjY1ODI3ODcvMzIxMTk1MDMwLTRkNjdhYWJlLWIyMjAtNGVjOC04NDc2LWU2MzhhM2ExMGJkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxNDM1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2ZmY2MzNDUwY2VlZTVkN2Y3MjA2ZDI3MTJlZWFkZmE2ZDRlOTYxNWE4N2E5ZTFkZjE2MWIzNTIwNmE5ZTk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xsIlFfUo2Ld7ETC4qBqGLtShDO-e93OR8R3gUmdBX6M">

contact me on discord: Silentsniper0
