### ISSUE TITLE
Performance per HW-Thread degrades the more HW-Threads used...

### ISSUE THREAD

**Issue by mutluit** [pooler/cpuminer#120] opened 2017-06-03 17:22 UTC
Hi pooler & all,
I think there is a performance issue in the thread handling.
For example, with just 1 thread it gives here (AMD A10-5750M APU, 4 HW threads) about 5200 khash/s.
But with 4 threads, each thread makes only about 3200 khash/s, ie. 12800 khash/s total.
I would have expected a nearly linear scaling, ie. 4 * 5200 = 20800 khash/s total.
Isn't it?

**Comment by pooler** [comment] 2017-06-03 18:06
Does this CPU have 4 cores or just 4 hardware threads? If the former, are they full cores or more like the "cores" of the Bulldozer microarchitecture?
Have you taken turbo into account?
What hash rates do you get with 2 and 3 threads?
Have you made sure that other processes aren't affecting your benchmarks?

**Comment by mutluit** [comment] 2017-06-03 19:00
I was thinking it has 4 HW-threads, but the CPU-spec says that it actually is just a dual core with 2 threads per core.
It scales only when max 2 threads are used (then each having the said 5200 kH/s).
So, it's then a CPU issue; case can be closed. Thx.

**Comment by pooler** [comment] 2017-06-03 21:05
I don't see anything funny about it, what Linux lists is logical CPUs (i.e., basically, hardware threads).
The term "core" does not have the exact same meaning across all microarchitectures. For instance it is possible that two cores share ALUs; that's one case where you wouldn't expect linear scaling with the number of threads.

**Comment by mutluit** [comment] 2017-06-03 23:20
I have a pure C code which I run in n threads.
In that code each thread works with its own stack data, ie. no semaphore/mutex required.
I get funny results: the performance of single thread gets divided when using multiple threads...:

$ ./a.out 1
0: n=10000000 clk=7311682 n/clk=1.36767 n/s=1367674.36002

$ ./a.out 2
0: n=10000000 clk=13678963 n/clk=0.73105 n/s=731049.56860
1: n=10000000 clk=13606278 n/clk=0.73495 n/s=734954.84952

$ ./a.out 3
0: n=10000000 clk=21966827 n/clk=0.45523 n/s=455231.88215
1: n=10000000 clk=23484336 n/clk=0.42582 n/s=425815.74374
2: n=10000000 clk=22886643 n/clk=0.43694 n/s=436936.07665

$ ./a.out 4
0: n=10000000 clk=32196747 n/clk=0.31059 n/s=310590.38356
1: n=10000000 clk=35316332 n/clk=0.28316 n/s=283155.11362
2: n=10000000 clk=35193300 n/clk=0.28414 n/s=284144.99351
3: n=10000000 clk=32932966 n/clk=0.30365 n/s=303647.11153

$ ./a.out 5
0: n=10000000 clk=36129908 n/clk=0.27678 n/s=276779.00536
1: n=10000000 clk=41885860 n/clk=0.23874 n/s=238744.05348
2: n=10000000 clk=44528658 n/clk=0.22457 n/s=224574.47516
3: n=10000000 clk=42872292 n/clk=0.23325 n/s=233250.88381
4: n=10000000 clk=39756378 n/clk=0.25153 n/s=251531.96803

This is maybe not related to cpuminer, but IMO still interessting.
Btw, happens both with pthreads in C as well with C++11 threads.

As mentioned, in cpuminer the scaling works at least for the # of cores,
but I think this happens only because of the asm code (here the sha256_4way) gets executed.
I think there is either a bug in pthreads, or that this AMD CPU is a total crap/scam.

**Comment by pooler** [comment] 2017-06-04 08:05
I don't know what implementation of SHA-256 you used, but if implemented correctly there should be few or no memory writes, and none to shared pages, so I doubt there can be any false sharing.

I took the time to look up your CPU, and here's what I found. It is a [Piledriver](https://en.wikipedia.org/wiki/Piledriver_(microarchitecture)) microarchitecture, and as I suspected it uses the same "module" design introduced by [Bulldozer](https://en.wikipedia.org/wiki/Bulldozer_(microarchitecture)). Each module has two "cores" which share various components, including the SIMD units. I think this pretty much explains your results.

**Comment by mutluit** [comment] 2017-06-04 11:16
Yes, that kind of AMD CPUs seem to crap.

Fyi, I tested the following (unoptimized) C code in multiple threads:
http://bradconte.com/sha256_c

**Comment by pooler** [comment] 2017-06-04 16:14
All right, I'm closing this as not a bug.

**Closed by pooler** 2017-06-04 16:14 UTC

**Comment by mutluit** [comment] 2017-06-04 16:42
pooler, just one more question: how do you count the hashrate in cpuminer? Is it the number of single sha256 hashes or is it the number of double hashes?

Thx for this pgm. I also had tested some other programs (cpuminer-multi, cpuminer-opt; I think they are derived/forked from yours), but they have memory leaks (can be seen after running half a day or so).

**Comment by pooler** [comment] 2017-06-04 17:15
Number of hashes of the selected algorithm, either scrypt or SHA-256d (in which case they're double hashes, in a sense).

**Comment by mutluit** [comment] 2017-06-05 10:34
Sorry to bother you, pooler, I know this is not a support board, but I don't have an acct at bitcoin.org yet, so forgive me to ask you just this final question if you allow:
when is work_restart signaled? If the currently worked on block has been found (by others) or if the server delivers additional/other transactions for the still worked on block?
Thank you.

**Comment by pooler** [comment] 2017-06-05 11:05
That is up to the server implementation. It could be in both cases.
