### ISSUE TITLE
LIBCURL_CHECK_CONFIG syntax error

### ISSUE THREAD

**Issue by neoriddle** [pooler/cpuminer#160] opened 2018-02-23 03:31 UTC
First I execute `./autogen.sh`, then `./configure CFLAGS="-O3"` and it throws:
```
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
...
checking whether we can compile AVX code... yes
checking whether we can compile XOP code... no
configure: WARNING: The assembler does not support the XOP instruction set.
checking whether we can compile AVX2 code... no
configure: WARNING: The assembler does not support the AVX2 instruction set.
checking for json_loads in -ljansson... no
checking for pthread_create in -lpthread... yes
./configure: line 5623: syntax error near unexpected token `,'
./configure: line 5623: `LIBCURL_CHECK_CONFIG(, 7.15.2, ,'
cpuminer-master$
```

**Comment by pooler** [comment] 2018-02-23 07:25
Duplicate of #37.

**Closed by pooler** 2018-02-23 07:25 UTC
