### ISSUE TITLE
Error line 5622 -> ./configure

### ISSUE THREAD

**Issue by D3m0nKingx** [pooler/cpuminer#107] opened 2016-05-28 14:36 UTC
after executing > ./configure CFLAGS="-O3"

the result:

checking for json_loads in -ljansson... yes
checking for pthread_create in -lpthread... yes
./configure: line 5622: syntax error near unexpected token `,'
./configure: line 5622: `LIBCURL_CHECK_CONFIG(, 7.15.2, ,'

Solution?

**Comment by pooler** [comment] 2016-05-28 14:40
Duplicate of #37.

**Closed by pooler** 2016-05-28 14:40 UTC
