### ISSUE TITLE
error ./configure no such file or directory

### ISSUE THREAD

**Issue by imtrynalearn** [pooler/cpuminer#234] opened 2021-05-29 05:35 UTC
while compiling on msys windows

**Comment by pooler** [comment] 2021-05-29 10:10
Assuming you're trying to build cpuminer, you'll have to provide more information on what steps you've followed.

**Comment by imtrynalearn** [comment] 2021-06-01 09:46
after ./configure got this error

```
./configure: line 5560: syntax error near unexpected token `,'
./configure: line 5560: `LIBCURL_CHECK_CONFIG(, 7.15.2, ,'
```

**Comment by pooler** [comment] 2021-06-01 10:08
Duplicate of #37. You'll need a full libcurl development package to build from the git repo. Alternatively, build from tarball.

**Closed as completed by pooler** 2021-06-01 10:08 UTC
